#include "mainwindow.h"
#include <QApplication>

#ifdef __linux__
#include <glib-2.0/glib.h> // for suppressing annoying glib object errors
#include <cstring>          // for parsing specific g_object_unref messages only

// Custom log handler to suppress specific messages caused by strange Qt multimedia and GStreamer behaviour
void my_log_handler(const gchar *log_domain,
                    GLogLevelFlags log_level,
                    const gchar *message,
                    gpointer user_data) {

    // Will suppress critical messages that contain "g_object_unref"
    // these are generated by some bizarre Qt 6 multimedia version VS GStreamer version interactions.
    // they are really annoying and harmless messages, for they got nothing to do with this app
    // depending on GStreamer version they do not even display. To enable them, comment the "if" block below.

    if (log_level & G_LOG_LEVEL_CRITICAL && message != nullptr) {
        if (strstr(message, "g_object_unref") != nullptr) {
            return; // Do nothing for messages containing "g_object_unref"
        }
    }

    // do Print all other messages!
    g_log_default_handler(log_domain, log_level, message, user_data);

}
#endif

int main(int argc, char *argv[]) {
#ifdef __linux__
    //g_type_init(); // uncomment to Initialize GLib (necessary for some GLib versions)
    g_log_set_default_handler(my_log_handler, NULL); // Set the custom log handler
#endif
#ifdef Q_OS_WIN
    qputenv("QT_MEDIA_BACKEND", "windows");
#endif
    QApplication WakkaQt(argc, argv);
    MainWindow w;
    w.show();
    return WakkaQt.exec();
}
