#include "sessionmanager.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QUuid>
#include <QDateTime>
#include <QDebug>
#include <algorithm>

SessionManager::SessionManager() {}

QString SessionManager::libraryRoot()
{
    return QDir::homePath() + "/.WakkaQt/library";
}

QString SessionManager::metaPath(const QString &sessionDir)
{
    return sessionDir + "/session.json";
}

bool SessionManager::copyFile(const QString &src, const QString &dst)
{
    if (src.isEmpty() || !QFile::exists(src)) {
        qWarning() << "SessionManager::copyFile: source does not exist:" << src;
        return false;
    }
    if (QFile::exists(dst) && !QFile::remove(dst)) {
        qWarning() << "SessionManager::copyFile: cannot remove existing dst:" << dst;
        return false;
    }
    if (!QFile::copy(src, dst)) {
        qWarning() << "SessionManager::copyFile: failed to copy" << src << "->" << dst;
        return false;
    }
    return true;
}

// QUuid::toString(WithoutBraces) never produces "..", "/", or "\", so this
// only ever rejects an id that didn't originate from saveSession() itself
// (e.g. hand-edited or otherwise tampered before reaching deleteSession()/
// renameSession()/restoreSession(), all of which build a filesystem path
// directly from libraryRoot() + "/" + id).
bool SessionManager::isValidSessionId(const QString &id)
{
    if (id.isEmpty() || id.contains('/') || id.contains('\\') || id.contains(".."))
        return false;
    return true;
}

// ── saveSession ───────────────────────────────────────────────────────────────
QString SessionManager::saveSession(
    const QString &webcamRecorded,
    const QString &audioRecorded,
    const QString &tunedRecorded,
    const QString &extractedTmpPlayback,
    const QString &currentVideoFile,
    const QString &currentVideoName,
    qint64 audioOffset,
    qint64 videoOffset,
    qint64 sysOffset)
{
    QDir dir;
    if (!dir.mkpath(libraryRoot())) {
        qWarning() << "SessionManager: cannot create library root" << libraryRoot();
        return {};
    }

    // Built entirely under a ".partial" directory and only renamed to its
    // final <id> name once every required file/metadata write has actually
    // succeeded — so a save that fails partway (disk full, permissions, a
    // copy that fails mid-transfer) can never leave a session that *looks*
    // complete to loadAll()/restoreSession() but is silently missing a file
    // or has stale metadata. Any failure below removes the partial directory
    // and returns {}, the same "failed" signal callers already handle.
    const QString id = QUuid::createUuid().toString(QUuid::WithoutBraces).left(12);
    const QString partialDir = libraryRoot() + "/" + id + ".partial";
    const QString finalDir   = libraryRoot() + "/" + id;

    auto abort = [&](const QString &reason) {
        qWarning() << "SessionManager: aborting save," << reason;
        QDir(partialDir).removeRecursively();
    };

    if (!dir.mkpath(partialDir)) {
        qWarning() << "SessionManager: cannot create session dir" << partialDir;
        return {};
    }

    const bool hasWebcam      = QFile::exists(webcamRecorded)
                             && QFileInfo(webcamRecorded).size() > 0;
    const bool hasAudio       = QFile::exists(audioRecorded)
                             && QFileInfo(audioRecorded).size() > 0;
    const bool hasPlaybackWav = QFile::exists(extractedTmpPlayback)
                             && QFileInfo(extractedTmpPlayback).size() > 0;

    // Each of these is only attempted if its source actually exists (that's
    // a legitimate "this session has no webcam" case, not a failure) — but
    // once attempted, it must succeed, or the whole save is rolled back.
    if (hasWebcam && !copyFile(webcamRecorded, partialDir + "/webcam.mkv")) {
        abort("webcam.mkv copy failed");
        return {};
    }
    if (hasAudio && !copyFile(audioRecorded, partialDir + "/audio.wav")) {
        abort("audio.wav copy failed");
        return {};
    }
    if (hasPlaybackWav && !copyFile(extractedTmpPlayback, partialDir + "/playback.wav")) {
        abort("playback.wav copy failed");
        return {};
    }
    // tuned.wav is intentionally NOT saved: it is always re-generated by
    // PreviewDialog from audio.wav with the user's current enhancement settings.

    // offsets.json — store qint64 as strings to avoid double precision loss.
    // QSaveFile writes to a temp file next to the target and only replaces it
    // on commit(), so a crash/power-loss mid-write can't corrupt/truncate it.
    {
        QJsonObject off;
        off["audioOffset"]  = QString::number(audioOffset);
        off["videoOffset"]  = QString::number(videoOffset);
        off["sysOffset"]    = QString::number(sysOffset);
        off["playbackFile"] = currentVideoFile;
        off["playbackName"] = currentVideoName;
        QSaveFile f(partialDir + "/offsets.json");
        if (!f.open(QIODevice::WriteOnly)
            || f.write(QJsonDocument(off).toJson()) < 0
            || !f.commit()) {
            abort("cannot write offsets.json");
            return {};
        }
    }

    // session.json — display metadata
    QString label;
    {
        label = currentVideoName
              + QString::fromUtf8(" \xe2\x80\x94 ")   // em dash
              + QDateTime::currentDateTime().toString("yyyy-MM-dd hh:mm");
        QJsonObject obj;
        obj["id"]          = id;
        obj["label"]       = label;
        obj["savedAt"]     = QDateTime::currentDateTime().toString(Qt::ISODate);
        obj["playbackFile"]= currentVideoFile;
        obj["playbackName"]= currentVideoName;
        obj["hasWebcam"]   = hasWebcam;
        obj["hasAudio"]    = hasAudio;

        QSaveFile f(partialDir + "/session.json");
        if (!f.open(QIODevice::WriteOnly)
            || f.write(QJsonDocument(obj).toJson()) < 0
            || !f.commit()) {
            abort("cannot write session.json");
            return {};
        }
    }

    if (!dir.rename(partialDir, finalDir)) {
        abort("cannot finalize session directory (rename)");
        return {};
    }

    qDebug() << "SessionManager: saved session" << id << "for" << currentVideoName;
    return id;
}

// ── readMetadata ──────────────────────────────────────────────────────────────
SessionEntry SessionManager::readMetadata(const QString &sessionDir)
{
    SessionEntry entry;
    entry.sessionDir = sessionDir;

    QFile f(sessionDir + "/session.json");
    if (!f.open(QIODevice::ReadOnly)) return entry;

    const QJsonDocument doc = QJsonDocument::fromJson(f.readAll());
    if (doc.isNull() || !doc.isObject()) return entry;

    const QJsonObject obj = doc.object();
    entry.id           = obj["id"].toString();
    entry.label        = obj["label"].toString();
    entry.savedAt      = QDateTime::fromString(obj["savedAt"].toString(), Qt::ISODate);
    entry.playbackFile = obj["playbackFile"].toString();
    entry.playbackName = obj["playbackName"].toString();
    entry.hasWebcam    = obj["hasWebcam"].toBool();
    entry.hasAudio     = obj["hasAudio"].toBool();
    return entry;
}

// ── writeMetadata — used by renameSession ─────────────────────────────────────
bool SessionManager::writeMetadata(const SessionEntry &entry)
{
    QFile f(metaPath(entry.sessionDir));

    // Preserve any unknown fields by reading first
    QJsonObject obj;
    if (f.open(QIODevice::ReadOnly)) {
        const QJsonDocument doc = QJsonDocument::fromJson(f.readAll());
        if (!doc.isNull() && doc.isObject())
            obj = doc.object();
        f.close();
    }

    obj["id"]          = entry.id;
    obj["label"]       = entry.label;
    obj["savedAt"]     = entry.savedAt.toString(Qt::ISODate);
    obj["playbackFile"]= entry.playbackFile;
    obj["playbackName"]= entry.playbackName;
    obj["hasWebcam"]   = entry.hasWebcam;
    obj["hasAudio"]    = entry.hasAudio;

    if (!f.open(QIODevice::WriteOnly)) {
        qWarning() << "SessionManager::writeMetadata: cannot open for writing:" << f.fileName();
        return false;
    }
    f.write(QJsonDocument(obj).toJson());
    return true;
}

// ── loadAll ───────────────────────────────────────────────────────────────────
QList<SessionEntry> SessionManager::loadAll()
{
    QList<SessionEntry> list;
    const QDir root(libraryRoot());
    if (!root.exists()) return list;

    for (const QString &sub : root.entryList(QDir::Dirs | QDir::NoDotAndDotDot)) {
        const QString sessionDir = libraryRoot() + "/" + sub;
        const SessionEntry e = readMetadata(sessionDir);
        if (!e.id.isEmpty())
            list.append(e);
    }

    std::sort(list.begin(), list.end(), [](const SessionEntry &a, const SessionEntry &b) {
        return a.savedAt > b.savedAt;
    });

    return list;
}

// ── deleteSession ─────────────────────────────────────────────────────────────
bool SessionManager::deleteSession(const QString &id)
{
    if (!isValidSessionId(id)) {
        qWarning() << "SessionManager::deleteSession: rejecting malformed id:" << id;
        return false;
    }
    const QString sessionDir = libraryRoot() + "/" + id;
    QDir dir(sessionDir);
    if (!dir.exists()) {
        qWarning() << "SessionManager::deleteSession: not found:" << sessionDir;
        return false;
    }
    return dir.removeRecursively();
}

// ── renameSession ─────────────────────────────────────────────────────────────
bool SessionManager::renameSession(const QString &id, const QString &newLabel)
{
    if (!isValidSessionId(id)) {
        qWarning() << "SessionManager::renameSession: rejecting malformed id:" << id;
        return false;
    }
    const QString sessionDir = libraryRoot() + "/" + id;
    SessionEntry e = readMetadata(sessionDir);
    if (e.id.isEmpty()) {
        qWarning() << "SessionManager::renameSession: session not found:" << id;
        return false;
    }
    e.label = newLabel;
    return writeMetadata(e);
}

// ── loadEntry ─────────────────────────────────────────────────────────────────
SessionEntry SessionManager::loadEntry(const QString &id)
{
    if (!isValidSessionId(id)) {
        qWarning() << "SessionManager::loadEntry: rejecting malformed id:" << id;
        return {};
    }
    return readMetadata(libraryRoot() + "/" + id);
}

// ── restoreSession ────────────────────────────────────────────────────────────
bool SessionManager::restoreSession(const QString &id,
                                    QString &webcamRecorded,
                                    QString &audioRecorded,
                                    QString &tunedRecorded,
                                    QString &extractedTmpPlayback,
                                    QString &currentVideoFile,
                                    QString &currentVideoName,
                                    qint64  &audioOffset,
                                    qint64  &videoOffset,
                                    qint64  &sysOffset)
{
    if (!isValidSessionId(id)) {
        qWarning() << "SessionManager::restoreSession: rejecting malformed id:" << id;
        return false;
    }
    const QString sessionDir = libraryRoot() + "/" + id;
    if (!QDir(sessionDir).exists()) {
        qWarning() << "SessionManager::restoreSession: dir not found:" << sessionDir;
        return false;
    }

    // Read offsets.json
    {
        QFile f(sessionDir + "/offsets.json");
        if (!f.open(QIODevice::ReadOnly)) {
            qWarning() << "SessionManager::restoreSession: cannot open offsets.json";
            // Non-fatal: continue, offsets stay at their current values
        } else {
            const QJsonObject off = QJsonDocument::fromJson(f.readAll()).object();
            audioOffset      = off["audioOffset"].toString().toLongLong();
            videoOffset      = off["videoOffset"].toString().toLongLong();
            sysOffset        = off["sysOffset"].toString().toLongLong();
            currentVideoFile = off["playbackFile"].toString();
            currentVideoName = off["playbackName"].toString();

            // The render only needs audio from the playback file; always use
            // the guaranteed local copy saved inside the session folder so
            // re-renders work regardless of whether the original file still exists.
            const QString localCopy = sessionDir + "/playback.wav";
            if (QFile::exists(localCopy))
                currentVideoFile = localCopy;
        }
    }

    // Copy artefacts back to their /tmp/ paths.
    // The destination paths (webcamRecorded etc.) always point to the same
    // fixed /tmp/WakkaQt_tmp_* locations; we never reassign them here.
    auto restoreOne = [&](const QString &srcName, const QString &dst) {
        const QString src = sessionDir + "/" + srcName;
        if (!QFile::exists(src)) {
            qDebug() << "SessionManager: optional file not in session:" << srcName;
            return;
        }
        if (QFile::exists(dst) && !QFile::remove(dst))
            qWarning() << "SessionManager: cannot remove old tmp file:" << dst;
        if (!QFile::copy(src, dst))
            qWarning() << "SessionManager: failed to restore" << srcName << "->" << dst;
        else
            qDebug() << "SessionManager: restored" << srcName << "->" << dst;
    };

    restoreOne("webcam.mkv",  webcamRecorded);
    restoreOne("audio.wav",   audioRecorded);
    restoreOne("playback.wav",extractedTmpPlayback);
    // tuned.wav is not saved/restored — PreviewDialog re-generates it from audio.wav

    qDebug() << "SessionManager: restore complete for session" << id
             << " | video:" << currentVideoName
             << " | audioOffset:" << audioOffset
             << " | videoOffset:" << videoOffset
             << " | sysOffset:"   << sysOffset;
    return true;
}
