#include "sessionrepository.h"
#include "complexes.h" // webcamRecorded/audioRecorded/extractedTmpPlayback fixed tmp paths

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QUuid>
#include <QDateTime>
#include <QDebug>
#include <algorithm>

SessionRepository::SessionRepository() {}

QString SessionRepository::libraryRoot()
{
    return QDir::homePath() + "/.WakkaQt/library";
}

QString SessionRepository::metaPath(const QString &sessionDir)
{
    return sessionDir + "/session.json";
}

bool SessionRepository::copyFile(const QString &src, const QString &dst)
{
    if (src.isEmpty() || !QFile::exists(src)) {
        qWarning() << "SessionRepository::copyFile: source does not exist:" << src;
        return false;
    }
    if (QFile::exists(dst) && !QFile::remove(dst)) {
        qWarning() << "SessionRepository::copyFile: cannot remove existing dst:" << dst;
        return false;
    }
    if (!QFile::copy(src, dst)) {
        qWarning() << "SessionRepository::copyFile: failed to copy" << src << "->" << dst;
        return false;
    }
    return true;
}

// QUuid::toString(WithoutBraces) never produces "..", "/", or "\", so this
// only ever rejects an id that didn't originate from saveSession() itself
// (e.g. hand-edited or otherwise tampered before reaching deleteSession()/
// renameSession()/restoreSession(), all of which build a filesystem path
// directly from libraryRoot() + "/" + id).
bool SessionRepository::isValidSessionId(const QString &id)
{
    if (id.isEmpty() || id.contains('/') || id.contains('\\') || id.contains(".."))
        return false;
    return true;
}

// ── saveSession ───────────────────────────────────────────────────────────────
SaveResult SessionRepository::saveSession(const SessionSnapshot &snapshot)
{
    SaveResult result;

    QDir dir;
    if (!dir.mkpath(libraryRoot())) {
        result.error = "cannot create library root " + libraryRoot();
        qWarning() << "SessionRepository:" << result.error;
        return result;
    }

    // Built entirely under a ".partial" directory and only renamed to its
    // final <id> name once every required file/metadata write has actually
    // succeeded — so a save that fails partway (disk full, permissions, a
    // copy that fails mid-transfer) can never leave a session that *looks*
    // complete to loadAll()/restoreSession() but is silently missing a file
    // or has stale metadata.
    const QString id = QUuid::createUuid().toString(QUuid::WithoutBraces).left(12);
    const QString partialDir = libraryRoot() + "/" + id + ".partial";
    const QString finalDir   = libraryRoot() + "/" + id;

    auto abort = [&](const QString &reason) {
        qWarning() << "SessionRepository: aborting save," << reason;
        QDir(partialDir).removeRecursively();
        result.error = reason;
    };

    if (!dir.mkpath(partialDir)) {
        result.error = "cannot create session dir " + partialDir;
        qWarning() << "SessionRepository:" << result.error;
        return result;
    }

    const bool hasWebcam      = QFile::exists(webcamRecorded)
                             && QFileInfo(webcamRecorded).size() > 0;
    const bool hasAudio       = QFile::exists(audioRecorded)
                             && QFileInfo(audioRecorded).size() > 0;
    const bool hasPlaybackWav = QFile::exists(extractedTmpPlayback)
                             && QFileInfo(extractedTmpPlayback).size() > 0;

    // Each of these is only attempted if its source actually exists (that's
    // a legitimate "this session has no webcam" case, not a failure) — but
    // once attempted, it must succeed, or the whole save is rolled back.
    if (hasWebcam && !copyFile(webcamRecorded, partialDir + "/webcam.mkv")) {
        abort("webcam.mkv copy failed");
        return result;
    }
    if (hasAudio && !copyFile(audioRecorded, partialDir + "/audio.wav")) {
        abort("audio.wav copy failed");
        return result;
    }
    if (hasPlaybackWav && !copyFile(extractedTmpPlayback, partialDir + "/playback.wav")) {
        abort("playback.wav copy failed");
        return result;
    }
    // tuned.wav is intentionally NOT saved: it is always re-generated by
    // PreviewDialog from audio.wav with the user's current enhancement settings.

    // offsets.json — store qint64 as strings to avoid double precision loss.
    // QSaveFile writes to a temp file next to the target and only replaces it
    // on commit(), so a crash/power-loss mid-write can't corrupt/truncate it.
    {
        QJsonObject off;
        off["audioOffset"]  = QString::number(snapshot.audioOffset);
        off["videoOffset"]  = QString::number(snapshot.videoOffset);
        off["sysOffset"]    = QString::number(snapshot.sysOffset);
        off["playbackFile"] = snapshot.currentVideoFile;
        off["playbackName"] = snapshot.currentVideoName;
        QSaveFile f(partialDir + "/offsets.json");
        if (!f.open(QIODevice::WriteOnly)
            || f.write(QJsonDocument(off).toJson()) < 0
            || !f.commit()) {
            abort("cannot write offsets.json");
            return result;
        }
    }

    // session.json — display metadata
    QString label;
    {
        label = snapshot.currentVideoName
              + QString::fromUtf8(" \xe2\x80\x94 ")   // em dash
              + QDateTime::currentDateTime().toString("yyyy-MM-dd hh:mm");
        QJsonObject obj;
        obj["id"]          = id;
        obj["label"]       = label;
        obj["savedAt"]     = QDateTime::currentDateTime().toString(Qt::ISODate);
        obj["playbackFile"]= snapshot.currentVideoFile;
        obj["playbackName"]= snapshot.currentVideoName;
        obj["hasWebcam"]   = hasWebcam;
        obj["hasAudio"]    = hasAudio;

        QSaveFile f(partialDir + "/session.json");
        if (!f.open(QIODevice::WriteOnly)
            || f.write(QJsonDocument(obj).toJson()) < 0
            || !f.commit()) {
            abort("cannot write session.json");
            return result;
        }
    }

    if (!dir.rename(partialDir, finalDir)) {
        abort("cannot finalize session directory (rename)");
        return result;
    }

    qDebug() << "SessionRepository: saved session" << id << "for" << snapshot.currentVideoName;
    result.ok = true;
    result.sessionId = id;
    return result;
}

// ── readMetadata ──────────────────────────────────────────────────────────────
SessionEntry SessionRepository::readMetadata(const QString &sessionDir)
{
    SessionEntry entry;
    entry.sessionDir = sessionDir;

    QFile f(sessionDir + "/session.json");
    if (!f.open(QIODevice::ReadOnly)) return entry;

    const QJsonDocument doc = QJsonDocument::fromJson(f.readAll());
    if (doc.isNull() || !doc.isObject()) return entry;

    const QJsonObject obj = doc.object();
    entry.id           = obj["id"].toString();
    entry.label        = obj["label"].toString();
    entry.savedAt      = QDateTime::fromString(obj["savedAt"].toString(), Qt::ISODate);
    entry.playbackFile = obj["playbackFile"].toString();
    entry.playbackName = obj["playbackName"].toString();
    entry.hasWebcam    = obj["hasWebcam"].toBool();
    entry.hasAudio     = obj["hasAudio"].toBool();
    return entry;
}

// ── writeMetadata — used by renameSession ─────────────────────────────────────
bool SessionRepository::writeMetadata(const SessionEntry &entry)
{
    QFile f(metaPath(entry.sessionDir));

    // Preserve any unknown fields by reading first
    QJsonObject obj;
    if (f.open(QIODevice::ReadOnly)) {
        const QJsonDocument doc = QJsonDocument::fromJson(f.readAll());
        if (!doc.isNull() && doc.isObject())
            obj = doc.object();
        f.close();
    }

    obj["id"]          = entry.id;
    obj["label"]       = entry.label;
    obj["savedAt"]     = entry.savedAt.toString(Qt::ISODate);
    obj["playbackFile"]= entry.playbackFile;
    obj["playbackName"]= entry.playbackName;
    obj["hasWebcam"]   = entry.hasWebcam;
    obj["hasAudio"]    = entry.hasAudio;

    if (!f.open(QIODevice::WriteOnly)) {
        qWarning() << "SessionRepository::writeMetadata: cannot open for writing:" << f.fileName();
        return false;
    }
    f.write(QJsonDocument(obj).toJson());
    return true;
}

// ── loadAll ───────────────────────────────────────────────────────────────────
QList<SessionEntry> SessionRepository::loadAll()
{
    QList<SessionEntry> list;
    const QDir root(libraryRoot());
    if (!root.exists()) return list;

    for (const QString &sub : root.entryList(QDir::Dirs | QDir::NoDotAndDotDot)) {
        const QString sessionDir = libraryRoot() + "/" + sub;
        const SessionEntry e = readMetadata(sessionDir);
        if (!e.id.isEmpty())
            list.append(e);
    }

    std::sort(list.begin(), list.end(), [](const SessionEntry &a, const SessionEntry &b) {
        return a.savedAt > b.savedAt;
    });

    return list;
}

// ── deleteSession ─────────────────────────────────────────────────────────────
OperationResult SessionRepository::deleteSession(const QString &id)
{
    OperationResult result;
    if (!isValidSessionId(id)) {
        result.error = "malformed session id";
        qWarning() << "SessionRepository::deleteSession: rejecting" << result.error << ":" << id;
        return result;
    }
    const QString sessionDir = libraryRoot() + "/" + id;
    QDir dir(sessionDir);
    if (!dir.exists()) {
        result.error = "session not found";
        qWarning() << "SessionRepository::deleteSession:" << result.error << ":" << sessionDir;
        return result;
    }
    if (!dir.removeRecursively()) {
        result.error = "could not remove session directory";
        qWarning() << "SessionRepository::deleteSession:" << result.error << ":" << sessionDir;
        return result;
    }
    result.ok = true;
    return result;
}

// ── renameSession ─────────────────────────────────────────────────────────────
OperationResult SessionRepository::renameSession(const QString &id, const QString &newLabel)
{
    OperationResult result;
    if (!isValidSessionId(id)) {
        result.error = "malformed session id";
        qWarning() << "SessionRepository::renameSession: rejecting" << result.error << ":" << id;
        return result;
    }
    const QString sessionDir = libraryRoot() + "/" + id;
    SessionEntry e = readMetadata(sessionDir);
    if (e.id.isEmpty()) {
        result.error = "session not found";
        qWarning() << "SessionRepository::renameSession:" << result.error << ":" << id;
        return result;
    }
    e.label = newLabel;
    if (!writeMetadata(e)) {
        result.error = "could not write session metadata";
        return result;
    }
    result.ok = true;
    return result;
}

// ── loadEntry ─────────────────────────────────────────────────────────────────
SessionEntry SessionRepository::loadEntry(const QString &id)
{
    if (!isValidSessionId(id)) {
        qWarning() << "SessionRepository::loadEntry: rejecting malformed id:" << id;
        return {};
    }
    return readMetadata(libraryRoot() + "/" + id);
}

// ── restoreSession ────────────────────────────────────────────────────────────
RestoreResult SessionRepository::restoreSession(const QString &id)
{
    RestoreResult result;

    if (!isValidSessionId(id)) {
        result.error = "malformed session id";
        qWarning() << "SessionRepository::restoreSession: rejecting" << result.error << ":" << id;
        return result;
    }
    const QString sessionDir = libraryRoot() + "/" + id;
    if (!QDir(sessionDir).exists()) {
        result.error = "session folder not found";
        qWarning() << "SessionRepository::restoreSession:" << result.error << ":" << sessionDir;
        return result;
    }

    // Neutral defaults: if offsets.json turns out to be missing/unreadable
    // below, restore must not leave these at whatever the caller happened to
    // have in memory from a previous recording/restore.
    SessionSnapshot &snapshot = result.snapshot;
    snapshot.audioOffset = 0;
    snapshot.videoOffset = 0;
    snapshot.sysOffset   = 0;
    snapshot.currentVideoFile.clear();
    snapshot.currentVideoName.clear();

    // Read offsets.json
    {
        QFile f(sessionDir + "/offsets.json");
        if (!f.open(QIODevice::ReadOnly)) {
            qWarning() << "SessionRepository::restoreSession: cannot open offsets.json";
            // Non-fatal: continue with the neutral defaults set above.
        } else {
            const QJsonObject off = QJsonDocument::fromJson(f.readAll()).object();
            snapshot.audioOffset      = off["audioOffset"].toString().toLongLong();
            snapshot.videoOffset      = off["videoOffset"].toString().toLongLong();
            snapshot.sysOffset        = off["sysOffset"].toString().toLongLong();
            snapshot.currentVideoFile = off["playbackFile"].toString();
            snapshot.currentVideoName = off["playbackName"].toString();

            // The render only needs audio from the playback file; always use
            // the guaranteed local copy saved inside the session folder so
            // re-renders work regardless of whether the original file still exists.
            const QString localCopy = sessionDir + "/playback.wav";
            if (QFile::exists(localCopy))
                snapshot.currentVideoFile = localCopy;
        }
    }

    // Ground-truth against the session folder itself, not any caller state:
    // this is what tells restoreAndRender() apart from "is a camera
    // currently plugged into this machine" (MainWindow::hasCamera), which
    // has nothing to do with what a given past session actually recorded.
    result.hasWebcam = QFile::exists(sessionDir + "/webcam.mkv");

    // Copy artefacts back to their /tmp/ paths, staged then swapped in one
    // pass — mirrors the same principle saveSession() uses (stage first,
    // only make the change visible once everything required has actually
    // succeeded), so a failure partway through never leaves a half-restored
    // mix of old and new tmp files, and is always reported to the caller.
    struct RestoreItem { const char *srcName; QString *dst; };
    const RestoreItem items[] = {
        { "webcam.mkv",   &webcamRecorded },
        { "audio.wav",    &audioRecorded },
        { "playback.wav", &extractedTmpPlayback },
    };
    constexpr int kCount = int(sizeof(items) / sizeof(items[0]));

    bool present[kCount];
    QString staged[kCount];

    // Stage phase: copy each file that exists in the session to a ".restoring"
    // sibling of its destination. The live tmp files are never touched here.
    for (int i = 0; i < kCount; ++i) {
        const QString src = sessionDir + "/" + items[i].srcName;
        present[i] = QFile::exists(src);
        if (!present[i]) {
            qDebug() << "SessionRepository: optional file not in session:" << items[i].srcName;
            continue;
        }

        const QString tmp = *items[i].dst + ".restoring";
        QFile::remove(tmp); // clear any leftover from a previous failed attempt
        if (!QFile::copy(src, tmp)) {
            result.error = QString("failed to stage %1").arg(items[i].srcName);
            qWarning() << "SessionRepository::restoreSession:" << result.error << "->" << tmp;
            for (int j = 0; j < i; ++j)
                if (present[j])
                    QFile::remove(staged[j]);
            return result;
        }
        staged[i] = tmp;
    }

    // Swap phase: every present file staged successfully, so make them all
    // visible. For files not part of this session, clear a stale tmp file
    // left over from a previous session/recording so nothing downstream
    // mistakes it for belonging to this restore.
    for (int i = 0; i < kCount; ++i) {
        QString *dst = items[i].dst;
        if (!present[i]) {
            if (QFile::exists(*dst) && !QFile::remove(*dst))
                qWarning() << "SessionRepository: cannot clear stale tmp file:" << *dst;
            continue;
        }
        if (QFile::exists(*dst) && !QFile::remove(*dst)) {
            result.error = QString("cannot remove old tmp file %1").arg(*dst);
            qWarning() << "SessionRepository::restoreSession:" << result.error;
            QFile::remove(staged[i]);
            return result;
        }
        if (!QFile::rename(staged[i], *dst)) {
            result.error = QString("failed to finalize %1").arg(*dst);
            qWarning() << "SessionRepository::restoreSession:" << result.error;
            return result;
        }
        qDebug() << "SessionRepository: restored" << items[i].srcName << "->" << *dst;
    }
    // tuned.wav is not saved/restored — PreviewDialog re-generates it from audio.wav

    qDebug() << "SessionRepository: restore complete for session" << id
             << " | hasWebcam:" << result.hasWebcam
             << " | video:" << snapshot.currentVideoName
             << " | audioOffset:" << snapshot.audioOffset
             << " | videoOffset:" << snapshot.videoOffset
             << " | sysOffset:"   << snapshot.sysOffset;
    result.ok = true;
    return result;
}
